# Set 1 to starting index
set -g base-index 1


# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on


# Keybindings to switch pane
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R


# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window


# reload config file
bind r source-file ~/.tmux.conf


# Theme, strongly inspired by github.com/PeterMosmans/dotfiles
set -g default-terminal "screen-256color"


# Dracula theme colors in use, with the following colors:
# background   darkest grey   colour17    #282a36 (mode line itself)
# current line dark grey      colour59    #44475a
# selection    dark grey      colour59    #44475a
# foreground   cream white    colour231   #f8f8f2
# comment      dark blue      colour61    #6272a4
# cyan         cyan           colour117   #8be9fd
# green        green          colour84    #50fa7b
# orange       orange         colour215   #ffb86c
# pink         pink           colour212   #ff79ca
# purple       purple         colour141   #bd93f9
# red          red            colour203   #ff5555
# yellow       yellow         colour228   #f1fa8c

# default inactive statusbar colors
# Dracula theme
set-option -g status-bg "#282a36"  # Background
set-option -g status-fg "#f8f8f2"  # Foreground
set-option -g status-attr default

# pane border
set-option -g pane-border-fg colour228
set-option -g pane-active-border-fg colour203

# message text
set-option -g message-bg "#ff5555"  # Red
set-option -g message-fg "#282a36"  # Background
set-option -g message-attr bright

# pane number display
set-option -g display-panes-active-colour blue
set-option -g display-panes-colour brightred

# Selected window
set-option -g window-status-current-format "#[bg=#44475a,fg=#282a36]#[bg=#44475a,fg=#f1fa8c,bold]#I:#[bg=#44475a,fg=#f1fa8c]#W#[bg=#282a36,fg=#44475a]"
# Inactive window
set-option -g window-status-format "#[bg=#44475a,fg=#282a36]#[bg=#44475a,fg=colour231]#I #W#[bg=#282a36,fg=#44475a]"

# Remove padding at the left hand side
set -g status-left ""
# Show a clock at the right hand side
set -g status-right "#[bg=#282a36,fg=#6272a4,bold]#[bg=#6272a4,fg=#f8f8f2] %H:%M "
