idle_bg = "#171817"
idle_fg = "#CCCCCC"
info_bg = "#B7A78E"
info_fg = "#e3dbc9"
good_bg = "#61A842"
good_fg = "#e3dbc9"
warning_bg = "#948475"
warning_fg = "#e3dbc9"
critical_bg = "#A1917F"
critical_fg = "#e3dbc9"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"