idle_bg = "#0f0d0e"
idle_fg = "#CCCCCC"
info_bg = "#586869"
info_fg = "#afbebc"
good_bg = "#323D42"
good_fg = "#afbebc"
warning_bg = "#38464A"
warning_fg = "#afbebc"
critical_bg = "#2A5564"
critical_fg = "#afbebc"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"