#!/usr/bin/env python3
import os

path = f"{os.environ['HOME']}/.cache/wal/colors"
file = open(path, 'r')
content = file.readlines()
file.close()

# variables = [ "idle_bg", "idle_fg", "info_bg", "info_fg", "good_bg", "good_fg", "warning_bg", "warning_fg", "critical_bg", "critical_fg", "separator", "separator_bg", "separator_fg"] 

result = f"idle_bg = \"{content[0][:-1]}\"\n"
#result += f"idle_fg = \"{content[8][:-1]}\"\n"
result += f"idle_fg = \"#CCCCCC\"\n"

result += f"info_bg = \"{content[5][:-1]}\"\n"
result += f"info_fg = \"{content[7][:-1]}\"\n"

result += f"good_bg = \"{content[1][:-1]}\"\n"
result += f"good_fg = \"{content[7][:-1]}\"\n"

result += f"warning_bg = \"{content[2][:-1]}\"\n"
result += f"warning_fg = \"{content[7][:-1]}\"\n"

result += f"critical_bg = \"{content[3][:-1]}\"\n"
result += f"critical_fg = \"{content[7][:-1]}\"\n"

result += "separator = \"\\ue0b2\"\n"
result += "separator_bg = \"auto\"\n"
result += "separator_fg = \"auto\"\n"


f = open("wal.toml", "w")
f.write(result[:-1])
f.close()
